name: Create or Update PR Comment

description: Create and update a PR comment, rather than creating a new one with every run.

inputs:
  github-token:
    required: true
    description: The GitHub token for interacting with the repository.

  comment-identifier:
    required: true
    description: An unchanging identifier for the comment that should be updated

  comment-content:
    required: true
    description: A string of Github-flavored markdown for your comment

  pr-ref:
    required: false
    description: A git ref which points to a commit contained in the target PR

  pr-num:
    required: false
    description: The number for the target PR

runs:
  using: 'node16'
  main: 'dist/index.js'
