name: 'JavaScript Action Template'

description: 'Add description here'

inputs:
  github-token:
    required: true
    description: The GitHub token for interacting with the repository.

  comment-identifier:
    required: true
    description: An unchanging identifier for the comment that should be updated

  comment-content:
    required: true
    description: A string of Github-flavored markdown for your comment

runs:
  using: 'node16'
  main: 'dist/index.js'
